Table users as U {
  id bigint [pk, increment] // auto-increment
  slug string
  name string
  email string
  email_verified_at timestamp [null]
  is_active boolean [default: true]
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table roles {
  id bigint [pk, increment]
  company_id bigint [ref: > companies.id]
  name string
  icon_path text
  description text
  created_at timestamp
  updated_at timestamp
}

Table role_levels {
  id bigint [pk, increment]
  role_id bigint [ref: > roles.id]
  level bigint
  description string
  created_at timestamp
  updated_at timestamp
}

Table permissions {
  id bigint [pk, increment]
  name string
  description text
  created_at timestamp
  updated_at timestamp
}

Table role_has_permission {
  role_id bigint [ref:  > roles.id]
  permission_id bigint [ref:  > permissions.id]
}
Table user_has_role {
  user_id bigint [ref: - users.id]
  role_id bigint [ref: - roles.id]
}

Table companies {
  id bigint [pk, increment]
  user_id bigint [ref: - users.id]
  name string
  slug string [unique]
  icon_path text [null]
  logo_path text [null]
  vat_number string [null]
  phone_number string
  province string
  city string
  district string
  sub_district string
  zip_code integer
  address text
  company_information string [null]
  is_active boolean [default: true]
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
 }
 
 Table company_settings {
   id bigint [pk, increment]
   company_id bigint [ref:- companies.id]
   currency string [default: "IDR"]
   ccy_symbol string [default: "Rp"]
   ccy_symbol_plcmt symbol_plcmt [default: "before amount"]
   date_format date_format [default: "dd/mm/yy"]
   time_format time_format [default: "24 Hour"]
   time_zone string [default: "Asia/Jakarta"]
   editable_terms editable_terms [default: "by status"]
   editable_by_days integer [default: 7]
   editable_by_status string [default: "completed"]
   item_sku_prefix string [null]
   item_default_unit_id bigint
   invoice_format json [null]
   bill_format json [null]
   payment_format json [null]
   def_acc_sale_id bigint [ref: > accounts.id]
   def_acc_purch_id bigint [ref: > accounts.id]
   created_at timestamp
   updated_at timestamp
   deleted_at timestamp
 }
 
 Enum symbol_plcmt {
   "before amount"
   "after amunt"
 }
 
 Enum date_format {
   "mm/dd/yy"
   "dd/mm/yy"
   "mm-dd-yy"
   "dd-mm-yy"
 }
 
 Enum time_format {
   "24 hour"
   "12 hour"
 }
 
 Enum editable_terms {
   "by days"
   "by status"
 }
 
 Table contacts {
   id bigint [pk, increment]
   user_id bigint [ref: - users.id]
   group_id  bigint [ref: - contact_groups.id]
   company_id bigint [ref: > companies.id]
   is_can_login boolean [default: false]
   is_active boolean [default: true]
   is_verified boolean [default: false]
   contact_type contact_type [default: "customer"]
   is_individual boolean [default: true]
   name string 
   phone_number string
   email string [null]
   province string
   city string
   district string
   sub_district string
   zip_code integer
   address text
   created_at timestamp
   updated_at timestamp
   deleted_at timestamp
 }
 
 Enum contact_type {
  supplier
  customer
  partner
 }
 
 Table contact_groups {
   id bigint [pk, increment]
   company_id bigint [ref: > companies.id]
   selling_price_group bigint
   name string
   description text
   created_at timestamp
   updated_at timestamp
   deleted_at timestamp
 }
 
 Table balances {
   id bigint
   contact_id bigint [ref: - contacts.id]
   amount bigint
 }
 
 Table balance_histories {
   id bigint
   balance_id bigint [ref: > balances.id]
   note string
   amount bigint
 }
 
 Table item_waranties {
   id bigint [pk, increment]
   company_id bigint [ref: > companies.id]
   name string
   description text
   duration integer [default: 1]
   duration_type duration_type [default: "months"]
   created_at timestamp
   updated_at timestamp
   deleted_at timestamp
 }
 
 Enum duration_type {
   days
   months
   years
 }
 
 Table item_unit {
   id bigint [pk, increment]
   company_id bigint [ref: > companies.id]
   name string
   short_name string
   is_decimal boolean [default: false]
   created_at timestamp
   updated_at timestamp
   deleted_at timestamp
 }

Table categories {
  id bigint [pk, increment]
  is_system boolean [default: false]
  company_id bigint [null]
  category_type category_type 
  meta_tags json
  slug string [unique]
  name string
  image_path text [null]
  category_code string [null]
  description text [null]
  parent bigint [default: 0, ref: > categories.id]
  category_attribut json [null]
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Enum category_type {
  item
  notification
  blog
}

Table item_brand {
  id bigint [pk, increment]
  company_id bigint [ref: > companies.id ]
  meta_tags json
  slug string [unique]
  name string
  image_path text [null]
  description text[null]
}

Table items {
  id bigint [pk, increment]
  company_id bigint [ref: > companies.id ]
  item_brand_id bigint [ref: > item_brand.id ]
  categories_id bigint [ref: > categories.id ]
  item_waranties_id bigint [ref: > item_waranties.id ]
  meta_tags json
  slug string [unique]
  name string
  variant_combination json [note: "Ex. Color: Red, Size: L"]
  description text 
  short_description string [null]
  weight decimal [null]
  is_active boolean [default: true]
  is_managed_stock boolean [default: false]
  image_path text [null]
  brochure_path text [null]
  attribut json [null]
  item_type item_type [default: "single", note: "Jika memilih tipe package maka akan memliki relasi dengan item_package_details"]
  tags json
  parent bigint [default: 0, ref: > items.id]
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Enum item_type {
  service
  single
  variable
  package
}

 Table item_has_variant {
   id bigint [pk, increment]
   item_id bigint [ref: > items.id]
   variant_id bigint [ref: > item_variants.id]
   possible_value json
 }

Table item_variants {
  id bigint [pk, increment]
  company_id bigint [ref: > companies.id ]
  name string
  possible_value json
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}


Table item_package_details {
  id bigint [pk, increment]
  company_id bigint [ref: > companies.id ]
  item_id_package bigint [ref: - items.id]
  item_id json [note: "referensi dari item"]
  created_at timestamp
  updated_at timestamp
} 
 
Table item_selling_price_group {
  id bigint [pk, increment]
  company_id bigint [ref: > companies.id ]
  name string
  description string
  is_active boolean [default: true]
  created_at timestamp
  deleted_at timestamp
  updated_at timestamp
}

Table item_pricings {
  id bigint [pk, increment]
  item_id bigint [ref: > items.id]
  price integer
  group_price json  [note: "group_price_id => group_price, 1 => 20000"]
  default_tax_id bigint [default: 0]
  selling_account_id bigint [ref: > accounts.id ,note: "default sesuai dengan company_setting"]
  purchase_account_id bigint [ref: > accounts.id ,note: "default sesuai dengan company_setting"]
  created_at timestamp
  deleted_at timestamp
  updated_at timestamp
}

Table warehouses {
  id bigint [pk, increment]
  company_id bigint [ref: > companies.id ]
  parent bigint [default: 0, ref: > warehouses.id ]
  name string
  address text
  description text [null]
  phone_number string
  email string [null]
  is_active boolean [default: true]
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}
 
 Table inventories {
   id bigint [pk, increment]
   company_id bigint [ref: > companies.id ]
   item_id bigint [ref: > items.id ]
   warehouse_id bigint [ref: > warehouses.id ]
   item_unit bigint  [ref: > item_unit.id ]
   sku string [null]
   barcode string [null]
   stock integer
   cost integer [null]
   contact_id bigint [null, ref: > contacts.id, note: "supplier"]
   security_stock integer [default: 20]
   created_at timestamp
   updated_at timestamp
   deleted_at timestamp
 }

Table inventory_histories {
  id bigint [pk, increment]
  inventory_id bigint [ref: > inventories.id]
  item_id bigint [ref: > items.id]
  order_id string [ref: - orders.id]
  quantity integer
  note string
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table item_unit_convert_details {
  id bigint [pk, increment]
  item_id bigint [ref: > items.id]
  default_item_unit_id bigint [ref: > item_unit.id]
  conversion_value integer
  to_item_unit_id bigint [ref: > item_unit.id]
  price json
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

 Table taxes {
   id bigint [pk, increment]
   company_id bigint [ref: > companies.id]
   name string
   rate integer
   created_at timestamp
   updated_at timestamp
   deleted_at timestamp
 }
 
Table orders {
  id bigint [pk, increment]
  company_id bigint [ref: > companies.id]
  order_type order_type [default: "selling"]
  order_number string [note: "sesuai dengan company_settings"]
  user_id bigint [ref: > users.id, note: "created_by"]
  contact_id bigint [ref: > contacts.id]
  logistic_id bigint [ref: > logistics.id]
  logistic_service_id bigint [ref: > logistic_services.id]
  warehouse_id bigint [ref: > warehouses.id]
  discount_amount integer [null]
  is_repeat_order boolean [default: false]
  receipt string [null]
  shipping_fee integer [default: 0]
  shipping_address json [note: "province, city, district, sub_district, zip_code"]
  cod_fee integer [default: 0]
  status order_status [default: "order placed"]
  message_for_packer text [null]
  message_for_logistic text [null]
  qty_amount integer
  weight decimal
  amount integer
  order_note text [null]
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Enum order_type {
  "selling"
  "purchase"
}

Enum order_status {
  "order placed"
  "packed"
  "shipping"
  "awaiting receipt"
  "delivered"
  "awaiting payment"
  "completed"
  "cancelled"
  "declined"
  "refunded"
  "returns"
}

Table order_has_discount {
  id bigint
  order_id bigint [ref: > orders.id]
  discount_id bigint [ref: > discounts.id]
  rate integer [default: 0]
  amount integer [default: 0]
}

Table order_has_taxes {
  id bigint
  order_id bigint [ref: > orders.id]
  tax_id bigint [ref: > taxes.id]
  rate integer
  amount integer
}

Table discounts {
  id bigint [pk, increment]
  company_id bigint [ref: > companies.id]
  name string [null]
  code string [null]
  discount_type discount_type [default: "coupon code"]
  is_unlimited boolean [default: true]
  discount_limit integer [null]
  coupon_type coupon_type [default: "flat"]
  discount_fee integer [null]
  start_date timestamp
  end_date timestamp
  is_never_expired boolean [default: false]
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Enum discount_type {
  "coupon code"
  "promotion"
}

Enum coupon_type {
  "flat"
  "percentage"
  "free shipping"
  "same price"
}

Table order_details {
  id bigint [pk, increment]
  order_id bigint [ref: > orders.id]
  item_id bigint [ref: > items.id]
  item_unit_id bigint [ref: > item_unit.id]
  item_note string [null]
  cust_rate integer [note: "harga barang satuan sesuai unit"]
  partner_rate integer [note: "harga barang satuan sesuai unit"]
  quantity integer
  weight decimal
  cust_amount integer
  partner_amount integer
  tax_id bigint [ref: > taxes.id]
  tax_amount integer
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table logistics {
  id bigint [pk, increment]
  company_id bigint [ref: > companies.id]
  is_system boolean [default: false]
  name string
  code string
  image_path text
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table logistic_services {
  id bigint [pk, increment]
  logistic_id bigint [ref: > logistics.id]
  name string
  is_req_receipt boolean [default: false]
  cod_fee integer
  discount_fee integer
  returns_fee_formula text
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table invoices {
  id bigint [pk, increment]
  company_id bigint [ref: > companies.id]
  invoice_number string [note: "sesuai dengan company_settings"]
  order_id bigint [ref: - orders.id]
  cust_contact_id bigint [ref: > contacts.id]
  cust_payment_method payment_method [default: "transfer"]
  cust_payment_status payment_status [default: "unpaid"]
  cust_terms_type terms_type
  cust_terms integer [default: 3]
  partner_payment_method payment_method [default: "transfer"]
  partner_payment_status payment_status [default: "unpaid"]
  partner_contact_id bigint [ref: > contacts.id]
  partner_terms_type terms_type
  partner_terms integer [default: 3]
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Enum terms_type {
  "days"
  "days after status is completed"
}

Enum payment_method {
  cod
  marketplace
  transfer
}

Enum payment_status {
  unpaid
  partially
  paid
}

Table bills {
  id bigint [pk, increment]
  company_id bigint [ref: > companies.id]
  bill_number string [note: "sesuai dengan company_settings"]
  order_id bigint [ref: - orders.id]
  payement_method payment_method [default: "transfer"]
  payment_status payment_status [default: "unpaid"]
  terms_type terms_type
  terms integer [default: 3]
  contact_id bigint [ref: > contacts.id, note: "contact status supplier"]
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table payment_histories {
  id bigint [pk, increment]
  number string [note: "Invoice / Bill Number"]
  from_account_id bigint [null, ref: > accounts.id]
  to_account_id bigint [null, ref: > accounts.id]
  created_by bigint [ref: > users.id] 
  amount integer
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table accounts {
  id bigint [pk, increment]
  company_id bigint [ref: > companies.id]
  parent bigint [default: 0, ref: > accounts.id]
  account_root account_root
  is_group boolean [default: false]
  name string
  account_type_id bigint [ref: > account_type.id]
  balance bigint [null]
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Enum account_root {
  "Assets"
  "Expenses"
  "Income"
  "Liabilities"
}

Table account_type {
  id bigint [pk, increment]
  company_id bigint [null, ref: > companies.id]
  name string [note: "Accumulated Depreciation, Bank, Cash, Chargeable,
  Cost of Goods Sold, Depreciation, Equity, Expense Account, 
  Expenses Included In Valuation, Fixed Asset, Income Account, Payable, Receivable,
  Round Off, Stock, Stock Adjustment, Stock Received But Not Billed, Tax, Temporary"]
  type boolean [note: "plus or minus"]
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table attachment {
  id bigint [pk, increment]
  company_id bigint [ref: > companies.id]
  model string
  model_id bigint 
  location text
  name string
  size integer
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table pivot_company_selling {
  company_id bigint [ref: - companies.id]
  order_id bigint [ref: - orders.id ]
}

Table pivot_company_purchasing {
  company_id bigint [ref: - companies.id]
  order_id bigint [ref: - orders.id]
}

Table system_notification {
  id bigint [pk, increment]
  is_system boolean [default: false]
  company_id bigint [null]
  categories bigint [ref: > categories.id]
  name string
  slug string
  description text
  is_active boolean [default: true]
  start_date timestamp
  end_date timestamp
  created_by bigint [ref: > users.id]
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table notifications {
  id uuid [pk, increment]
  company_id bigint [ref: > companies.id]
  string type
  notifiable morphs
  data text
  read_at timestamp
  created_at timestamp
  updated_at timestamp
}

Table blog {
  id bigint [pk, increment]
  is_system boolean [default: false]
  company_id bigint [null]
  categories bigint [ref: > categories.id]
  meta_tags json
  title string
  slug string
  content text
  status boolean [default: false]
  created_by bigint [ref: > users.id]
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table page {
  id bigint [pk, increment]
  is_system boolean [default: false]
  company_id bigint [null]
  meta_tags json
  title string
  content text
  status boolean [default: true]
  page_type page_type
  created_by bigint [ref: > users.id]
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Enum page_type {
  about
  terms
  return_terms
  other
}

Table exporting_files {
  id bigint [pk, increment]
  company_id bigint [ref: > companies.id]
  applicant_id bigint [ref: > users.id]
  sent_to string
  file_type file_type
  file_name string
  file_location text
  file_size bigint
  requested_at timestamp
  downloaded_at timestamp
  expired_at timestamp
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Enum file_type {
  csv 
  pdf 
  excel
}

Table import_templates {
  id bigint [pk, increment]
  name string
  template_for string
  file_location text
  file_size string
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table importing_files {
  id bigint [pk, increment]
  company_id bigint [ref: > companies.id]
  imported_by bigint [ref: > users.id]
  file_name string
  file_size string
  file_origin_location text
  imported_at timestamp
  succeed_at timestamp [null]
  created_at timestamp
  updated_at timestamp
  deleted_at timestamp
}

Table importing_note {
  id bigint [pk, increment]
  importing_files_id bigint [ref: > importing_files.id]
  exception_data json
  created_at timestamp
  updated_at timestamp
}
